spring:
  application:
    name: graphql-poc
    version: replaceVersion
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: ${DB_URL}           - задается в TestContainersInitializer
#    username: ${DB_USERNAME} - задается в TestContainersInitializer
#    password: ${DB_PASSWORD} - задается в TestContainersInitializer
  jpa:
    generate-ddl: false  # только ручное создание объектов БД
    show-sql: false # дубликат, см. logging ниже
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yaml

# embedded Tomcat
server:
  port: 9900

logging:
  level:
    org.apache.http: INFO
    org.springframework.transaction.interceptor: WARN # поставить в TRACE для получения информации по транзакциям
    org.hibernate:
        SQL: debug
        type: trace
    root: info
    org.springframework.graphql: debug

myservice:
  send-transactions-faults-num: 0     # сколько нужно имитировать системных сбоев при коммитах транзакций Kafka на отправку сообщений
  receive-transactions-faults-num: 0  # сколько нужно имитировать системных сбоев при коммитах транзакций Kafka на получение сообщений
  business-faults: true               # имитировать ли сбои в бизнес-логике
  topics:
    main-topic: my-topic