spring:
  application:
    name: graphql-poc
    version: replaceVersion
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: ${DB_URL}           - задается в TestContainersInitializer
#    username: ${DB_USERNAME} - задается в TestContainersInitializer
#    password: ${DB_PASSWORD} - задается в TestContainersInitializer
  jpa:
    generate-ddl: false  # только ручное создание объектов БД
    show-sql: false # дубликат, см. logging ниже
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yaml
  kafka:
    #    bootstrap-servers: - задается в TestContainersInitializer
    consumer:
      group-id: myconsumergroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.lanit.research.kafkascaling.sender.adapter.kafka.dto,ru.lanit.research.kafkascaling.receiver.adapter.kafka.dto
        spring.json.value.default.type: ru.lanit.research.graphql.adapter.kafka.dto.KafkaGraphQlRequest # для упрощения считаем, что у нас один тип DTO для входящих сообщений
        isolation.level: read_committed
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false # не шлем тип DTO (java class)

# embedded Tomcat
server:
  port: 9900

logging:
  level:
    org.apache.http: INFO
    org.springframework.transaction.interceptor: WARN # поставить в TRACE для получения информации по транзакциям
    org.hibernate:
        SQL: debug
        type: trace
    root: info
    org.springframework.graphql: debug

myservice:
  topics:
    main-topic: my-topic